from tkinter import *
master = Tk()
v = IntVar()
options = []
for i in range(10, 31):
    options.append(i)
Label(master, text="Regno").grid(row=0)
Label(master, text="Name").grid(row=1)
Label(master, text="Dept").grid(row=2)
Label(master, text="Gender").grid(row=3)
Label(master, text="Age").grid(row=4)
menu = StringVar()
menu.set("Select Your Age")
# entry fields
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
r1 = Radiobutton(master, text="Male", variable=v, value=1)
r2 = Radiobutton(master, text="Female", variable=v, value=2)
drop = OptionMenu(master, menu, *options)
b1 = Button(master, text="Insert")
b2 = Button(master, text="Update")
b3 = Button(master, text="Delete")
b4 = Button(master, text="Select")
# Place fields
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
r1.grid(row=3, column=1)
r2.grid(row=3, column=2)
drop.grid(row=4, column=1)
b1.grid(row=5, column=0)
b2.grid(row=5, column=1)
b3.grid(row=6, column=0)
b4.grid(row=6, column=1)
mainloop()
