from tkinter import *
master = Tk()
v = IntVar()
options = []
for i in range(10, 31):
    options.append(i)
Label(master, text="Custid").grid(row=0)
Label(master, text="Customer Name").grid(row=1)
Label(master, text="Branch").grid(row=2)
Label(master, text="Account type").grid(row=3)
Label(master, text="Amount").grid(row=4)
# entry fields
e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
r1 = Radiobutton(master, text="Saving", variable=v, value=1)
r2 = Radiobutton(master, text="Non Saving", variable=v, value=2)
b1 = Button(master, text="Insert")
b2 = Button(master, text="Update")
b3 = Button(master, text="Delete")
b4 = Button(master, text="Select")
s1 = Scale(master, from_=0, to=100, orient=HORIZONTAL)
# Place fields
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
r1.grid(row=3, column=1)
r2.grid(row=3, column=2)
b1.grid(row=5, column=0)
b2.grid(row=5, column=1)
b3.grid(row=6, column=0)
b4.grid(row=6, column=1)
s1.grid(row=4, column=1)
mainloop()
